config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :constrollers => { 
    :registrations => "users/registrations", 
    :sessions => "users/sessions",
    :passwords => "users/passwords" }
  devise_scope :user do
    get 'signup' =>  'users/registrations#new'
    get 'signin' =>  'users/sessions#new'
    get 'signout' => 'users/sessions#destroy'
    get 'search' => 'users#index'
  end

  # root is only a main page

  root 'posts#index', as: 'home' #  controller that controlls showing # controller's method that calls to view(html) pattern; method.name=view(html).name

  # get - all other pages

  get 'about' => 'pages#about', as: 'about'
  get 'profile/:id' => 'pages#profile', as: 'profile'

  # resources allows to track all the controller's actions (GET, DELETE, ...)
  # use RESOURCE when routes don't need id, when we don't need index action

  resources :posts do # allowed all actions just in case :)
    resources :comments, only: [:create, :destroy] # allows to have routes like 'post/1/comment/5' 
  end

  # I don't put likes under :posts like :comments because maybe I'll need to make likes polymorphic(Ex. likes to comments)
  resources :likes, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, presence: true, length: {minimum: 2} #  presence: true means that validates automatically 
  validates :picture, presence: true
  #after_commit :post_created_email, on: :create  
  #after_commit :post_updated_email, on: :update 
  mount_uploader :picture, PictureUploader
  
  def author?(user)
    user == self.user
  end

  private

  #def post_created_email
  #  PostMailer.with(post: self).new_post_email.deliver
  #end

  #def post_updated_email
  #  PostMailer.with(post: self).edit_post_email.deliver
  #end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    # select * from posts where post.user_id
    follows = current_user.following_follows.select('following_id')
    @posts = Post.includes(:user).where("user_id in (?)", follows).limit(50).order(id: :desc)
    # @posts = Post.includes(:user).all.limit(50).order(id: :desc)
  end

  def new # if you wanna check all actions from resources: 'rake routes'
    @post = Post.new
  end 

  def show
    @post= Post.find(params[:id])
  end

  def edit
    @post= Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    authorize @post

    if @post.update(post_params)
      redirect_to post_path(@post) # calls 'show'
    else
      render :edit # rerender the current page
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    
    if(@post.save)
      redirect_to post_path(@post) # calls 'show'
    else
      render :new # rerender the current page
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    authorize @post
    @post.picture.remove!
    @post.destroy
    redirect_to home_path # home_path == posts_path
  end

  private def post_params
    params.require(:post).permit(:title, :body, :picture)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<!-- we need this kinda pattern because we have more than 1 similar forms -->
<div class="new-post">
<%= form_for @post, html: { multipart: true } do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"> <%= msg %> </div>
    <% end %>
  <% end %>  

  <p>
    Title: <br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    Text: <br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
    
  <p>
    Image: 
    <div class="image-uploader"> 
      <%= f.file_field(:picture, { :class => 'form-control'}) %>
    </div>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-lg btn-outline-pink'}, {:id => 'new'}) %>
    <!-- <%= link_to 'Back', posts_path, :class => "btn btn-lg btn-outline-pink" %> -->
    <%= link_to "Back", :back, class: 'btn btn-lg btn-outline-pink'%>
  </p>
<% end %>
</div>

app/views/posts/_likes.html.erb
<div class="col-md-4 text-start mobile-button" style="margin-left:10px">
  <% like = current_user.likes.find_by(post: post) %>
  <% if like.nil? %>
    <%= form_with model: @like, url: likes_path, method: :create do |f| %>   
      <input type="hidden" name="like[post_id]" value="<%= post.id %>">
      <%= hidden_field :like, { :value => @like } %>
      <div class="row">
        <%= button_tag( :class => "btn btn-lg btn-outline-pink") do %>
          <i class="bi-heart" style="font-style: normal"> 
            <%= Like.where(post_id: post.id).count %> 
          </i>
        <% end %>
      </div>
    <% end %>
  <% else %>
    
   <!-- likes' deletion -->

    <div class="row">
      <%= link_to like_path(like), method: :delete, remote: true, class: "btn btn-lg btn-outline-pink" do %>
        <i class="bi-heart-fill" style="font-style: normal">
          <%= Like.where(post_id: post.id).count %>
        </i>  
      <% end %>   
    </div>
  <% end %>
</div>    

app/views/posts/_profile_link.erb
<%= link_to profile_path(user.id), class: "no-decoration" do %> 
    <% if user.avatar.url.nil? %>
      <%= text_field_tag "", 'No avatar', class: 'avatar-show avatar-show-small cursor-pointer' %>
    <% else %>
      <span>
        <%= image_tag user.avatar.url(:large), class: 'avatar-show avatar-show-small'%>
      </span>
    <% end %>
    <%= user.username %>
<% end %>

app/views/posts/edit.html.erb
<div class="card mb-4 rounded-3 shadow-sm">
  <div class="card-body">
    <center class="profile-name"> 
      Edit Post 
    </center>
    <%= render 'form', post: @post %>
  </div>
</div>

app/views/posts/index.html.erb
<% if @posts.empty? %>
  <div class="card mb-4 rounded-3 shadow-sm" style="margin-top: 10%">
    <div class="card-body">
      <center class="profile-name"> 
        Welcome to 
        <img class="logo" src='https://github.com/sharedmean/ruby-course-project/blob/master/app/assets/images/logo.png?raw=true'> 
        </img>  
        !<br>
        <hr> 
        <span style="font-size:20px"> 
          You don't have your feed yet, but it's easy to fix! <br> 
            Click on Search icon above to see all 
            <img class="logo" src='https://github.com/sharedmean/ruby-course-project/blob/master/app/assets/images/logo.png?raw=true'> 
            </img>  
            users <br>
          or <br>
          Enter your friend's username in the text field above and then click Search icon 
          <hr>
        </span>
        Have fun in 
        <img class="logo" src='https://github.com/sharedmean/ruby-course-project/blob/master/app/assets/images/logo.png?raw=true'> 
        </img>  
        !<br>
      </center>
    </div>
  </div>
<% else %>
  <% @posts.each do |post| %>
    <div class="card mb-4 rounded-3 shadow-sm">
      <div class="card-body">

        <!-- link to post's author profile -->

        <p class="fw-bold">
          <%= render 'profile_link', user: post.user %> 
        </p>   
        
        <!-- post -->

        <p><%= image_tag post.picture.url(:large), class: 'content-img img-show', alt: post.title if post.picture? %></p>
        <b> <%= post.title %> </b> 
        <p> <%= post.body %> </p>
        <hr>
        <div class="row">

          <!-- comments button -->

          <div class="col-md-1 text-start mobile-button">
            <%= link_to post_path(post), class: "btn btn-lg btn-outline-pink" do %>
              <i class="bi-chat" ></i>  
            <% end %>
          </div>

          <!-- likes button -->

          <div class="col-md-3 text-start mobile-button">      
            <%= render 'likes', post: post %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<div class="card mb-4 rounded-3 shadow-sm">
  <div class="card-body">
    <center class="profile-name"> 
      Add New Post 
    </center>
    <%= render 'form', post: @post %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="card mb-4 rounded-3 shadow-sm">
  <div class="card-body">

    <!-- link to post's author profile -->

    <p class="fw-bold">
      <%= render 'profile_link', user: @post.user %>
    </p>  

    <!-- post -->

    <p><%= image_tag @post.picture.url(:large), class: 'content-img img-show', alt: @post.title if @post.picture? %></p> 
    <b> <%= @post.title %> </b> 
    <p> <%= @post.body %> </p>
    <hr>
    <div class="col-md-3 text-start">
      <div class="row">

        <!-- likes button -->

        <%= render 'likes', post: @post %>

        <!-- edit and delete buttons -->

        <% if user_signed_in? %>
          <% if policy(@post).edit? %>
            <div class="col-md-3 text-start mobile-button">    
              <%= link_to edit_post_path(@post), class: "btn btn-lg btn-outline-pink" do %>
                <i class="bi-pen" ></i>  
              <% end %>
            </div>
            <div class="col-md-3 text-start mobile-button">
              <%= link_to post_path(@post), method: :delete, 
                  data: {confirm: "Delete post?"}, class: "btn btn-lg btn-outline-pink" do %>
                <i class="bi-trash" ></i>  
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <hr>

    <!-- comments -->

    <div class="card-body">
      <% @post.comments.each do |comment| %>
        <div class="card mb-2 rounded-5 shadow-sm">
          <div style="padding:10px">
            <% user = User.find(comment.user_id) %>
            <p> 

            <!-- link to post's author profile -->

            <%= render 'profile_link', user: user %> 

            <!-- destroy comment button -->

            <% if policy(comment).destroy? %>
              <%= 
                link_to post_comment_path(@post, comment), method: :delete, 
                data: {confirm: "Delete comment?"}, class: "btn btn-sm btn-outline-pink no-margin" do %>
                  <i style="font-size:12px;text-align:right" class="bi-trash" ></i>  
              <% end %>
            <% end %>

            <!-- comment -->

            <p> <%= comment.body %> </p>
            </p>
          </div>
        </div>
      <% end %>
      
      <!-- new comment form -->

      <%= form_with model: @post.comments.build, url: [@post, @post.comments.build], method: :create do |f| %>   
        <p>
          Comment <br>
          <%= f.text_area(:body, {:class => 'form-control'}) %>
        </p>  
        <p>
          <%= f.submit("Send", {:class => 'btn btn-lg btn-outline-pink'}) %> <!-- submit calls create method -->
          <% if params[:profile]=="profile_path" %>
            <%= link_to "Back to profile", profile_path(@post.user), class: 'btn btn-lg btn-outline-pink'%>
          <% else %>
            <%= link_to 'Back to posts', posts_path, :class => "btn btn-lg btn-outline-pink" %> 
          <% end %>
        </p>
      <% end %>
    </div>
  </div>
</div>