config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :constrollers => { 
    :registrations => "users/registrations", 
    :sessions => "users/sessions",
    :passwords => "users/passwords" }
  devise_scope :user do
    get 'signup' =>  'users/registrations#new'
    get 'signin' =>  'users/sessions#new'
    get 'signout' => 'users/sessions#destroy'
    get 'search' => 'users#index'
  end

  # root is only a main page

  root 'posts#index', as: 'home' #  controller that controlls showing # controller's method that calls to view(html) pattern; method.name=view(html).name

  # get - all other pages

  get 'about' => 'pages#about', as: 'about'
  get 'profile/:id' => 'pages#profile', as: 'profile'

  # resources allows to track all the controller's actions (GET, DELETE, ...)
  # use RESOURCE when routes don't need id, when we don't need index action

  resources :posts do # allowed all actions just in case :)
    resources :comments, only: [:create, :destroy] # allows to have routes like 'post/1/comment/5' 
  end

  # I don't put likes under :posts like :comments because maybe I'll need to make likes polymorphic(Ex. likes to comments)
  resources :likes, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :likes
  validates :body, presence: true, length: {minimum: 3} #  presence: true means that validates automatically 

  def author?(user)
    user == self.user
  end
end

app/models/follow.rb
class Follow < ApplicationRecord
  require 'composite_primary_keys'
  set_primary_keys :follower_id, :following_id
  belongs_to :follower, foreign_key: "follower_id", class_name: "User"
  belongs_to :following, foreign_key: "following_id", class_name: "User"  

  def different?(follow)
    follow.following_id != follow.follower_id
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  # that's for one like to one post
  # the uniqueness is also made on db level using indexes
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, presence: true, length: {minimum: 2} #  presence: true means that validates automatically 
  validates :picture, presence: true
  #after_commit :post_created_email, on: :create  
  #after_commit :post_updated_email, on: :update 
  mount_uploader :picture, PictureUploader
  
  def author?(user)
    user == self.user
  end

  private

  #def post_created_email
  #  PostMailer.with(post: self).new_post_email.deliver
  #end

  #def post_updated_email
  #  PostMailer.with(post: self).edit_post_email.deliver
  #end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes
  mount_uploader :avatar, PictureUploader
  validates :username, presence: true, length: {minimum: 4}
  validates_uniqueness_of :username
  validates_uniqueness_of :email

  has_many :follower_follows, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_follows, source: :follower

  has_many :following_follows, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followings, through: :following_follows, source: :following

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to @post
    else
      flash[:notice] = "An error has occured during your comment creation. Please, try again."
      redirect_to @post
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    authorize @comment
    @comment.destroy
    redirect_to @post  
  end

  private def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    @follow = Follow.new(follow_params)
    authorize @follow
    @follow.save
     
    respond_to do |format|
      format.js { render inline: "location.reload();" }
    end 
  end
  
  def destroy
    @follow = current_user.following_follows.find_by(following_id: params[:id])
    @follow.destroy
    
    respond_to do |format|
      format.js { render inline: "location.reload();" }
    end 
  end

  private def follow_params
    params.require(:follow).permit(:following_id, :follower_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new(like_params)
    @like.save

    respond_to do |format|
      format.js { render inline: "location.reload();" }
    end 
  end
  
  def destroy
    @like = current_user.likes.find(params[:id])
    @like.destroy
    
    respond_to do |format|
      format.js { render inline: "location.reload();" }
    end 
  end

  private def like_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < PostsController
  def profile
    @post = Post.includes(:user).where(user_id: params[:id]).order(id: :desc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    # select * from posts where post.user_id
    follows = current_user.following_follows.select('following_id')
    @posts = Post.includes(:user).where("user_id in (?)", follows).limit(50).order(id: :desc)
    # @posts = Post.includes(:user).all.limit(50).order(id: :desc)
  end

  def new # if you wanna check all actions from resources: 'rake routes'
    @post = Post.new
  end 

  def show
    @post= Post.find(params[:id])
  end

  def edit
    @post= Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    authorize @post

    if @post.update(post_params)
      redirect_to post_path(@post) # calls 'show'
    else
      render :edit # rerender the current page
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    
    if(@post.save)
      redirect_to post_path(@post) # calls 'show'
    else
      render :new # rerender the current page
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    authorize @post
    @post.picture.remove!
    @post.destroy
    redirect_to home_path # home_path == posts_path
  end

  private def post_params
    params.require(:post).permit(:title, :body, :picture)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:username]
      @users = User.where('username LIKE ?', "%#{params[:username]}%")
    elsif params[:user_follower_id]
      follows = User.find(params[:user_follower_id]).following_follows.select('following_id')
      @users = User.where("id in (?)", follows)
    elsif params[:user_following_id]
      follows = User.find(params[:user_following_id]).follower_follows.select('follower_id')
      @users = User.where("id in (?)", follows)
    else
      @users = User.all
    end
  end   
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    # Il8n - json translation module
    sentence = I18n.t("errors.messages.not_saved",
                        count: resource.errors.count,
                        resource: resource.class.model_name.human.downcase)
    html = <<-HTML
    <div class="alert alert-danger">
      #{sentence}
    </div>
    <div class="alert-error alert-block register-error">
      #{messages}
    </div>
    HTML
    html.html_safe
  end
end

app/helpers/follow_helper.rb
module FollowHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<header id="header" class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 ">
  
  <!-- logo -->
  <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
    <svg xmlns="http://www.w3.org/2000/svg" width="36" fill="#ee538d" class="bi bi-instagram" viewBox="0 0 16 16">
      <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
    </svg>
      <img class="logo" src='https://github.com/sharedmean/ruby-course-project/blob/master/app/assets/images/logo.png?raw=true'> 
      </img> 
  </a>
  <!-- search field -->
  <%= form_tag(search_path, method: :get) do %>
    <p class="input-group" style="margin-left: 14%;">
      <%= text_field_tag :username, params[:username], value: '', placeholder:"Search", :class => 'form-control search no-decoration' %>
      <%= button_tag( :class => "btn btn-lg btn-outline-pink search-button input-group-text", type: 'submit') do %>
                <i class="bi-search" style="font-style: normal"> 
                </i>
              <% end %>
    </p>
  <% end %> 
  <!-- buttons -->   
     
  <div class="col-md-4 text-end">
    <% if user_signed_in? %>
  
      <%= link_to new_post_path, class: "btn btn-lg btn-outline-pink profile-add-icons" do %>
        <i class="bi-plus-lg" style="font-size:25px;"></i> 
      <% end %>
     
        
      <%= link_to profile_path(User.find(current_user.id).id), class: "btn btn-lg btn-outline-pink profile-add-icons" do %>
        <i class="bi-person-fill" style="font-size:25px;"></i> 
      <% end %> 

      <%= link_to destroy_user_session_path, :method => :delete, :class => "btn btn-lg btn-outline-pink exit-icon" do %>
        <i class="bi-box-arrow-in-right" style="font-size:26px;"></i> 
      <% end %>

    <% else %>
      <button type="button" class="btn btn-lg btn-outline-pink">
      <%= link_to 'Log in', signin_path %> 
      </button>
      <button type="button" class="btn btn-lg btn-outline-pink">
      <%= link_to 'Sign up', signup_path %>
      </button>
    <% end %> 
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PinkSta</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
    <!-- Bootstrap Font Icon CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" media="all" href="/assets/mob.css">
  </head>
  
  <%= render 'layouts/header' %>
  <body>
    

    <% if notice %>
      <p class="alert"> <%= notice %> </p>
    <% end %>

    <% if alert %>
      <p class="alert"> <%= alert %> </p> 
    <% end %>
    

    <div class="container content">
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/about.html.erb
<!-- Don't use this page now, but saved it just in case -->
<h1> <%= @title %> </h1>

app/views/pages/profile.html.erb
<div class="card mb-4 rounded-3 shadow-sm">
  <div class="card-body">  
      <% user =  User.find(params[:id]) %>
        <div class="row" >

          <!-- avatar -->

          <div class="col-lg-3 text-start">
            <% if user.avatar.url.nil? %>
              <p class="avatar-show avatar-show-big no-avatar cursor-pointer">
                No avatar
              </p>
            <% else %>
              <p>
                <%= image_tag user.avatar.url(:large), class: 'avatar-show avatar-show-big'%>
              </p>
            <% end %>
          </div>
          <div class="col">
            <div class="row">

              <!-- username -->

              <div class="col-md-6 text-end profile-header padding">
                <span class="profile-name"> 
                  <%= user.username %> 
                </span>
              </div>

              <!-- follow/unfollow button -->

              <% if !(current_user.id==user.id) %>
                <div class="col-lg-5 text-start profile-header">
                  <% follow = current_user.following_follows.find_by(following_id: user.id) %>
                  <% if follow.nil? %>
                    <%= form_with model: @follow, url: follows_path, method: :create do |f| %>   
                      <input type="hidden" name="follow[following_id]" value="<%= user.id %>">
                      <input type="hidden" name="follow[follower_id]" value="<%= current_user.id %>">
                      <div class="col-lg-5 text-start">
                        <%= button_tag( :class => "btn btn-lg btn-outline-pink") do %>
                          Follow
                        <% end %>
                      </div>
                    <% end %>
                  <% else %>
                    <div class="col-lg-5 text-start">
                      <%= link_to follow_path(follow.following_id), method: :delete, remote: true, class: "btn btn-lg btn-outline-pink" do %>
                        Unfollow 
                      <% end %>   
                    </div>
                  <% end %>
                </div>
              <% else %> 

                <!-- edit profile button -->

                <div class="col-lg-5 text-start profile-header">
                  <button type="button" class="btn btn-lg btn-outline-pink">
                    <%= link_to 'Edit profile', edit_user_registration_path %>
                  </button>
                </div>
              <% end %>
            </div>
            <hr> 
            <div class="row" style="margin-top:30px; margin-bottom:30px; justify-content:space-around">

              <!-- followings button -->

              <div class="col-lg-3 ml-7 profile-bottons">      
                <%= form_tag(search_path, method: :get) do %>
                  <input type="hidden" name="user_follower_id" value="<%= user.id %>">
                  <%= button_tag( :class => "btn btn-lg btn-outline-pink profile-circle", type: 'submit', name: nil,) do %>
                    <i class="bi-bookmark-heart" style="font-style: normal; font-size:24px;"> 
                      <%= user.following_follows.size %>
                    </i>
                    followings
                  <% end %>
                <% end %>  
              </div>

              <!-- posts' size -->

              <div class="col-lg-3 profile-circle profile-bottons">
                  <i class="bi-instagram" style="font-style: normal; font-size:24px;"> 
                    <%= @post.size %>
                  </i> 
                  <br>
                  posts
              </div>

              <!-- followers button -->

              <div class="col-lg-3 profile-bottons">      
                <%= form_tag(search_path, method: :get) do %>
                  <input type="hidden" name="user_following_id" value="<%= user.id %>">
                  <%= button_tag( :class => "btn btn-lg btn-outline-pink profile-circle", type: 'submit', name: nil,) do %>
                    <i class="bi-person-check" style="font-style: normal; font-size:24px;"> 
                      <%= user.follower_follows.size %>
                    </i>
                    followers
                  <% end %>
                <% end %>  
              </div>
            </div>  
          </div>
        </div>
    <hr> 
    
    <!-- user's posts -->

    <div class="card-body">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-2">
        <% @post.each do |post| %>
          <div class="col">
            <%= link_to post_path(post, profile: "profile_path") do %>
                <%= image_tag post.picture.url(:large), class: 'content-img-profile img-show', alt: post.title if post.picture? %>
            <% end %>
          </div>
        <% end %>
      </div>
      <hr>
    
    </div>
  </div>
</div>